name: demo_actions
on:
  workflow_dispatch:
jobs:
  beforeinstall:
    runs-on: ['self-hosted','Linux','X64','react']
    steps:
      - name: repository pull
        run: cd /home/react/Image-compressor-react-app/ && git pull origin master
      - name: run script to install package and run app
        run: cd /home/react/ && bash run.sh
